#!/bin/bash
#
# kolmnurk paremalt vasakule
#
for((r=1; r<6; r++))
do
  # tärnid
  for((v=1; v<$((6-$r+1));  v++))
  do
    echo -n "  "
  done
  #täpid
  for ((v=1; v<$r; v++))
  do
    echo -n "+ "
  done
  # plussid
  for ((v=1; v<$(($r+1)); v++))
  do
    echo -n "+ "
  done
  #kui rida lõpeb -reavahetus
  echo
done
