#!/bin/bash
#
# muutujate kasutamise näide
#
# defineerime muutuja ja omistame väärtus
# väärtus saadetakse whoami käsust
kasutaja=`whoami`
# väljastame muutuja väärtuse koos seletusega
echo "Tere, $kasutaja!"
# loome ja väljastame kellaaja
kell=`date +'%H:%M'`
echo "kell on $kell"
